# Generated by Django 4.1.6 on 2023-02-07 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 7, 19, 44, 51, 28059)),
            preserve_default=False,
        ),
    ]
